console.log(typeof Number("10"));
console.log(typeof Math.PI);
console.log(typeof Number("Hello"));
let a = Number("Hello");
console.log(typeof a);
console.log(typeof NaN);
console.log(typeof Number(""));
console.log(typeof Number(" "));
console.log(Number(""));
console.log(Number(" "));
console.log(Number("Hello"));
console.log(Number("-10.10"));
console.log(Number("years 10"));
console.log(Number("10 years"));
console.log("---------------------- parseInt -----------------");
console.log(parseInt("six"));
console.log(parseInt("10.10") + " - lost a decimal");
console.log(parseInt("-10.10"));
console.log(parseFloat("-10.10"));
console.log(parseInt("-10.10"));
console.log(parseInt("years 10"));
console.log(parseInt("10 years"));
console.log("------------------------- + ----------------------");
console.log(+"-10.10");
console.log(+"years 10");
console.log(+"10 years");
